import type { AppRoute } from "@/types/route";

export const routeRegistry = [
  {
    id: "home",
    path: "/",
    labelKey: "nav.home",
    component: "home",
    seo: {
      titleKey: "seo.home.title",
      descriptionKey: "seo.home.description",
      keywords: ["Moenotes", "BanG Dream! Our Notes", "Our Notes database", "Our Notes cards", "Our Notes music", "StarMoe", "star.moe"],
      sitemap: { priority: 1, changefreq: "daily" },
    },
    nav: false,
    searchable: true,
    keywords: ["home", "index", "moenotes"],
  },
  {
    id: "database",
    path: "/database",
    labelKey: "nav.groups.database",
    seo: {
      titleKey: "seo.database.title",
      descriptionKey: "seo.database.description",
      keywords: ["BanG Dream! Our Notes database", "Our Notes data", "Our Notes characters", "Our Notes cards", "Our Notes songs", "StarMoe", "star.moe"],
      sitemap: { priority: 0.8, changefreq: "daily" },
    },
    nav: { order: 10, icon: "database", shortcut: "g d" },
    searchable: true,
    keywords: ["database", "data", "masterdata"],
    children: [
      {
        id: "characters",
        path: "/characters",
        labelKey: "nav.items.characters",
        component: "characters",
        seo: {
          titleKey: "seo.characters.title",
          descriptionKey: "seo.characters.description",
          keywords: ["BanG Dream! Our Notes characters", "Our Notes character list", "Our Notes bands", "character profiles", "birthdays", "band members"],
          sitemap: { priority: 0.8, changefreq: "daily" },
        },
        nav: { order: 10, icon: "users", shortcut: "g c" },
        searchable: true,
        keywords: ["characters", "members", "cast"],
        children: [
          {
            id: "character-detail",
            kind: "dynamic",
            path: "/characters/:id",
            pattern: "/characters/:id",
            parentId: "characters",
            labelKey: "nav.items.characters",
            component: "character-detail",
            seo: {
              titleKey: "seo.characterDetail.title",
              descriptionKey: "seo.characterDetail.description",
            },
            nav: false,
            searchable: false,
            staticParams: async () => (await import("@/lib/route/masterdata-params")).getMasterdataDetailParams("characters"),
          },
        ],
      },
      {
        id: "cards",
        path: "/cards",
        labelKey: "nav.items.cards",
        component: "cards",
        seo: {
          titleKey: "seo.cards.title",
          descriptionKey: "seo.cards.description",
          keywords: ["BanG Dream! Our Notes cards", "Our Notes card list", "card artwork", "card rarity", "card attributes", "Our Notes gacha"],
          sitemap: { priority: 0.8, changefreq: "daily" },
        },
        nav: { order: 15, icon: "sparkles" },
        searchable: true,
        keywords: ["cards", "illustration", "gacha"],
        children: [
          {
            id: "card-detail",
            kind: "dynamic",
            path: "/cards/:id",
            pattern: "/cards/:id",
            parentId: "cards",
            labelKey: "nav.items.cards",
            component: "card-detail",
            seo: {
              titleKey: "seo.cardDetail.title",
              descriptionKey: "seo.cardDetail.description",
            },
            nav: false,
            searchable: false,
            staticParams: async () => (await import("@/lib/route/masterdata-params")).getMasterdataDetailParams("cards"),
          },
        ],
      },
      {
        id: "support-cards",
        path: "/support-cards",
        labelKey: "nav.items.supportCards",
        component: "support-cards",
        seo: {
          titleKey: "seo.supportCards.title",
          descriptionKey: "seo.supportCards.description",
          keywords: ["BanG Dream! Our Notes support cards", "Our Notes support card list", "support card artwork", "support card rarity", "support card attributes"],
          sitemap: { priority: 0.8, changefreq: "daily" },
        },
        nav: { order: 18, icon: "sparkles" },
        searchable: true,
        keywords: ["support cards", "support", "gacha"],
        children: [
          {
            id: "support-card-detail",
            kind: "dynamic",
            path: "/support-cards/:id",
            pattern: "/support-cards/:id",
            parentId: "support-cards",
            labelKey: "nav.items.supportCards",
            component: "support-card-detail",
            seo: {
              titleKey: "seo.supportCardDetail.title",
              descriptionKey: "seo.supportCardDetail.description",
            },
            nav: false,
            searchable: false,
            staticParams: async () => (await import("@/lib/route/masterdata-params")).getMasterdataDetailParams("support-cards"),
          },
        ],
      },
      {
        id: "gacha",
        path: "/gacha",
        labelKey: "nav.items.gacha",
        component: "gacha",
        seo: {
          titleKey: "seo.gacha.title",
          descriptionKey: "seo.gacha.description",
          keywords: ["BanG Dream! Our Notes gacha", "Our Notes gacha pools", "gacha rates", "pickup cards", "gacha schedule"],
          sitemap: { priority: 0.8, changefreq: "daily" },
        },
        nav: { order: 19, icon: "sparkles" },
        searchable: true,
        keywords: ["gacha", "draw", "pool", "pickup", "banner"],
        children: [
          {
            id: "gacha-detail",
            kind: "dynamic",
            path: "/gacha/:id",
            pattern: "/gacha/:id",
            parentId: "gacha",
            labelKey: "nav.items.gacha",
            component: "gacha-detail",
            seo: {
              titleKey: "seo.gachaDetail.title",
              descriptionKey: "seo.gachaDetail.description",
            },
            nav: false,
            searchable: false,
            staticParams: async () => (await import("@/lib/route/masterdata-params")).getMasterdataDetailParams("gacha"),
          },
        ],
      },
      {
        id: "music",
        path: "/music",
        labelKey: "nav.items.music",
        component: "music",
        seo: {
          titleKey: "seo.music.title",
          descriptionKey: "seo.music.description",
          keywords: ["BanG Dream! Our Notes songs", "Our Notes music", "song list", "chart difficulty", "chart constants", "song credits"],
          sitemap: { priority: 0.8, changefreq: "daily" },
        },
        nav: { order: 20, icon: "music", shortcut: "g m" },
        searchable: true,
        keywords: ["music", "songs", "live"],
        children: [
          {
            id: "song-detail",
            kind: "dynamic",
            path: "/music/:id",
            pattern: "/music/:id",
            parentId: "music",
            labelKey: "nav.items.music",
            component: "song-detail",
            seo: {
              titleKey: "seo.songDetail.title",
              descriptionKey: "seo.songDetail.description",
            },
            nav: false,
            searchable: false,
            staticParams: async () => (await import("@/lib/route/masterdata-params")).getMasterdataDetailParams("music"),
          },
        ],
      },
      {
        id: "stamps",
        path: "/stamps",
        labelKey: "nav.items.stamps",
        component: "stamps",
        seo: {
          titleKey: "seo.stamps.title",
          descriptionKey: "seo.stamps.description",
          keywords: ["BanG Dream! Our Notes stamps", "Our Notes stickers", "character stamps", "sticker artwork", "emoji assets"],
          sitemap: { priority: 0.8, changefreq: "daily" },
        },
        nav: { order: 22, icon: "sparkles" },
        searchable: true,
        keywords: ["stamps", "stickers", "emojis"],
      },
      {
        id: "rewards",
        path: "/rewards",
        labelKey: "nav.items.rewards",
        component: "rewards",
        seo: {
          titleKey: "seo.rewards.title",
          descriptionKey: "seo.rewards.description",
          keywords: ["BanG Dream! Our Notes season pass", "Our Notes login bonus", "limited missions", "season pass rewards", "mission rewards"],
          sitemap: { priority: 0.7, changefreq: "daily" },
        },
        nav: { order: 21, icon: "calendar" },
        searchable: true,
        keywords: ["season pass", "login bonus", "missions", "rewards"],
        children: [
          {
            id: "reward-detail",
            kind: "dynamic",
            path: "/rewards/:id",
            pattern: "/rewards/:id",
            parentId: "rewards",
            labelKey: "nav.items.rewards",
            component: "reward-detail",
            seo: {
              titleKey: "seo.rewardDetail.title",
              descriptionKey: "seo.rewardDetail.description",
            },
            nav: false,
            searchable: false,
            staticParams: async () => (await import("@/lib/route/masterdata-params")).getMasterdataRewardParams(),
          },
        ],
      },
      {
        id: "titles",
        path: "/titles",
        labelKey: "nav.items.titles",
        component: "titles",
        seo: {
          titleKey: "seo.titles.title",
          descriptionKey: "seo.titles.description",
          keywords: ["BanG Dream! Our Notes titles", "Our Notes profile stickers", "title unlock conditions", "character rank rewards", "profile card"],
          sitemap: { priority: 0.6, changefreq: "weekly" },
        },
        nav: { order: 23, icon: "sparkles" },
        searchable: true,
        keywords: ["titles", "degrees", "profile stickers"],
      },
      {
        id: "backgrounds",
        path: "/backgrounds",
        labelKey: "nav.items.backgrounds",
        component: "backgrounds",
        seo: {
          titleKey: "seo.backgrounds.title",
          descriptionKey: "seo.backgrounds.description",
          keywords: ["BanG Dream! Our Notes backgrounds", "Our Notes profile backgrounds", "profile card backgrounds", "background artwork"],
          sitemap: { priority: 0.6, changefreq: "weekly" },
        },
        nav: { order: 24, icon: "palette" },
        searchable: true,
        keywords: ["backgrounds", "profile", "wallpaper"],
      },
      {
        id: "comics",
        path: "/comics",
        labelKey: "nav.items.comics",
        component: "comics",
        seo: {
          titleKey: "seo.comics.title",
          descriptionKey: "seo.comics.description",
          keywords: ["BanG Dream! Our Notes comics", "Our Notes manga", "loading screen comics", "four-panel comics", "comic artwork"],
          sitemap: { priority: 0.8, changefreq: "daily" },
        },
        nav: { order: 25, icon: "book" },
        searchable: true,
        keywords: ["comics", "manga", "loading screen"],
      },
      {
        id: "items",
        path: "/items",
        labelKey: "nav.items.items",
        component: "items",
        seo: {
          titleKey: "seo.items.title",
          descriptionKey: "seo.items.description",
          keywords: ["BanG Dream! Our Notes items", "Our Notes item list", "game materials", "inventory items", "item artwork"],
          sitemap: { priority: 0.8, changefreq: "daily" },
        },
        nav: { order: 26, icon: "archive" },
        searchable: true,
        keywords: ["items", "possessions", "materials", "inventory"],
      },
    ],
  },
  {
    id: "story",
    path: "/story",
    labelKey: "nav.groups.story",
    seo: {
      titleKey: "seo.story.title",
      descriptionKey: "seo.story.description",
      keywords: ["BanG Dream! Our Notes story", "Our Notes stories", "main story", "bond stories", "story transcripts", "character voices"],
      sitemap: { priority: 0.7, changefreq: "weekly" },
    },
    nav: { order: 30, icon: "book", shortcut: "g s" },
    searchable: true,
    keywords: ["story", "scenario"],
    children: [
      {
        id: "main-story",
        path: "/story/main",
        labelKey: "nav.items.mainStory",
        component: "story-main",
        seo: {
          titleKey: "seo.mainStory.title",
          descriptionKey: "seo.mainStory.description",
          keywords: ["BanG Dream! Our Notes main story", "Our Notes story chapters", "main scenario", "story transcript", "character voices"],
          sitemap: { priority: 0.6, changefreq: "weekly" },
        },
        nav: { order: 10, icon: "book" },
        searchable: true,
        keywords: ["main story", "scenario"],
      },
      {
        id: "friendship-story",
        path: "/story/friendship",
        labelKey: "nav.items.friendshipStory",
        component: "story-friendship",
        seo: {
          titleKey: "seo.friendshipStory.title",
          descriptionKey: "seo.friendshipStory.description",
          keywords: ["BanG Dream! Our Notes bond stories", "Our Notes friendship stories", "character bonds", "bond story transcript", "character voices"],
          sitemap: { priority: 0.6, changefreq: "weekly" },
        },
        nav: { order: 20, icon: "book" },
        searchable: true,
        keywords: ["friendship story", "link story", "scenario"],
      },
      {
        id: "other-story",
        path: "/story/other",
        labelKey: "nav.items.otherStory",
        component: "story-other",
        seo: {
          titleKey: "seo.otherStory.title",
          descriptionKey: "seo.otherStory.description",
          keywords: ["BanG Dream! Our Notes conversations", "post-live talks", "home conversations", "tutorial stories", "story transcripts"],
          sitemap: { priority: 0.5, changefreq: "weekly" },
        },
        nav: { order: 30, icon: "book" },
        searchable: true,
        keywords: ["post live", "home story", "tutorial story", "other story"],
      },
      {
        id: "story-detail",
        kind: "dynamic",
        path: "/story/:id",
        pattern: "/story/:id",
        parentId: "story",
        labelKey: "nav.groups.story",
        component: "story-detail",
        seo: { titleKey: "seo.storyDetail.title", descriptionKey: "seo.storyDetail.description" },
        nav: false,
        searchable: false,
        staticParams: async () => (await import("@/lib/route/masterdata-params")).getMasterdataStoryParams(),
      },
    ],
  },
  {
    id: "tools",
    path: "/tools",
    labelKey: "nav.groups.tools",
    seo: {
      titleKey: "seo.tools.title",
      descriptionKey: "seo.tools.description",
      keywords: ["Moenotes tools", "Our Notes tools", "BanG Dream database tools", "StarMoe tools", "star.moe tools"],
      sitemap: { priority: 0.6, changefreq: "weekly" },
    },
    nav: { order: 40, icon: "wrench", shortcut: "g t" },
    searchable: true,
    keywords: ["tools", "calculator"],
    children: [
      {
        id: "asset-viewer",
        path: "/tools/asset-viewer",
        labelKey: "nav.items.assetViewer",
        component: "asset-viewer",
        seo: {
          titleKey: "seo.assetViewer.title",
          descriptionKey: "seo.assetViewer.description",
          keywords: ["Our Notes assets", "BanG Dream asset viewer", "game asset browser", "card artwork assets", "music jacket assets"],
          sitemap: { priority: 0.5, changefreq: "weekly" },
        },
        nav: { order: 10, icon: "folder-open" },
        searchable: true,
        keywords: ["asset", "viewer", "s3", "files"],
      },
      {
        id: "design-system",
        path: "/tools/design-system",
        labelKey: "nav.items.designSystem",
        component: "design-system",
        seo: {
          titleKey: "seo.designSystem.title",
          descriptionKey: "seo.designSystem.description",
          sitemap: { priority: 0.3, changefreq: "monthly" },
          indexable: false,
        },
        nav: false,
        searchable: false,
        keywords: ["design system", "style guide", "components"],
      },
    ],
  },
  {
    id: "community",
    path: "/about",
    labelKey: "nav.groups.community",
    component: "about",
    seo: {
      titleKey: "seo.about.title",
      descriptionKey: "seo.about.description",
      keywords: ["Moenotes", "StarMoe", "star.moe", "BanG Dream! Our Notes database", "Our Notes viewer", "Moenotes project"],
      sitemap: { priority: 0.5, changefreq: "monthly" },
    },
    nav: { order: 50, icon: "info" },
    searchable: true,
    keywords: ["about", "StarMoe", "star.moe"],
    children: [],
  },
] as const satisfies readonly AppRoute[];
