import type { AppRoute } from "@/types/route";

export const routeRegistry = [
  {
    id: "home",
    path: "/",
    labelKey: "nav.home",
    seo: {
      titleKey: "seo.home.title",
      descriptionKey: "seo.home.description",
      keywords: ["Moenotes", "BanG Dream", "Our Notes", "MoeSekai"],
      sitemap: { priority: 1, changefreq: "daily" },
    },
    nav: false,
    searchable: true,
    keywords: ["home", "index", "moenotes"],
  },
  {
    id: "database",
    path: "/database",
    labelKey: "nav.groups.database",
    seo: {
      titleKey: "seo.database.title",
      descriptionKey: "seo.database.description",
      sitemap: { priority: 0.8, changefreq: "daily" },
    },
    nav: { order: 10, icon: "database", shortcut: "g d" },
    searchable: true,
    keywords: ["database", "data", "masterdata"],
    children: [
      {
        id: "characters",
        path: "/characters",
        labelKey: "nav.items.characters",
        seo: {
          titleKey: "seo.characters.title",
          descriptionKey: "seo.characters.description",
          sitemap: { priority: 0.8, changefreq: "daily" },
        },
        nav: { order: 10, icon: "users", shortcut: "g c" },
        searchable: true,
        keywords: ["characters", "members", "cast"],
      },
      {
        id: "music",
        path: "/music",
        labelKey: "nav.items.music",
        seo: {
          titleKey: "seo.music.title",
          descriptionKey: "seo.music.description",
          sitemap: { priority: 0.8, changefreq: "daily" },
        },
        nav: { order: 20, icon: "music", shortcut: "g m" },
        searchable: true,
        keywords: ["music", "songs", "live"],
      },
    ],
  },
  {
    id: "activity",
    path: "/activity",
    labelKey: "nav.groups.activity",
    seo: {
      titleKey: "seo.activity.title",
      descriptionKey: "seo.activity.description",
      sitemap: { priority: 0.7, changefreq: "daily" },
    },
    nav: { order: 20, icon: "calendar", shortcut: "g a" },
    searchable: true,
    keywords: ["activity", "events", "news"],
    children: [
      {
        id: "events",
        path: "/events",
        labelKey: "nav.items.events",
        seo: {
          titleKey: "seo.events.title",
          descriptionKey: "seo.events.description",
          sitemap: { priority: 0.8, changefreq: "daily" },
        },
        nav: { order: 10, icon: "calendar", shortcut: "g e" },
        searchable: true,
        keywords: ["events", "event"],
      },
      {
        id: "news",
        path: "/news",
        labelKey: "nav.items.news",
        seo: {
          titleKey: "seo.news.title",
          descriptionKey: "seo.news.description",
          sitemap: { priority: 0.6, changefreq: "daily" },
        },
        nav: { order: 20, icon: "newspaper" },
        searchable: true,
        keywords: ["news", "notice", "information"],
      },
    ],
  },
  {
    id: "story",
    path: "/story",
    labelKey: "nav.groups.story",
    seo: {
      titleKey: "seo.story.title",
      descriptionKey: "seo.story.description",
      sitemap: { priority: 0.7, changefreq: "weekly" },
    },
    nav: { order: 30, icon: "book", shortcut: "g s" },
    searchable: true,
    keywords: ["story", "scenario"],
    children: [
      {
        id: "main-story",
        path: "/story/main",
        labelKey: "nav.items.mainStory",
        seo: {
          titleKey: "seo.mainStory.title",
          descriptionKey: "seo.mainStory.description",
          sitemap: { priority: 0.6, changefreq: "weekly" },
        },
        nav: { order: 10, icon: "book" },
        searchable: true,
        keywords: ["main story", "scenario"],
      },
      {
        id: "event-story",
        path: "/story/events",
        labelKey: "nav.items.eventStory",
        seo: {
          titleKey: "seo.eventStory.title",
          descriptionKey: "seo.eventStory.description",
          sitemap: { priority: 0.6, changefreq: "weekly" },
        },
        nav: { order: 20, icon: "book" },
        searchable: true,
        keywords: ["event story", "scenario"],
      },
    ],
  },
  {
    id: "tools",
    path: "/tools",
    labelKey: "nav.groups.tools",
    seo: {
      titleKey: "seo.tools.title",
      descriptionKey: "seo.tools.description",
      sitemap: { priority: 0.6, changefreq: "weekly" },
    },
    nav: { order: 40, icon: "wrench", shortcut: "g t" },
    searchable: true,
    keywords: ["tools", "calculator"],
    children: [
      {
        id: "toolbox",
        path: "/tools/toolbox",
        labelKey: "nav.items.toolbox",
        seo: {
          titleKey: "seo.toolbox.title",
          descriptionKey: "seo.toolbox.description",
          sitemap: { priority: 0.5, changefreq: "weekly" },
        },
        nav: { order: 10, icon: "sparkles" },
        searchable: true,
        keywords: ["toolbox", "utilities"],
      },
    ],
  },
  {
    id: "community",
    path: "/about",
    labelKey: "nav.groups.community",
    seo: {
      titleKey: "seo.about.title",
      descriptionKey: "seo.about.description",
      sitemap: { priority: 0.5, changefreq: "monthly" },
    },
    nav: { order: 50, icon: "info" },
    searchable: true,
    keywords: ["about", "moesekai"],
    children: [],
  },
] as const satisfies readonly AppRoute[];
