import type { AppRoute } from "@/types/route";
import { CARD_IDS } from "@/lib/cards/constants";
import { SUPPORT_CARD_IDS } from "@/lib/support-cards/constants";
import { MUSIC_IDS } from "@/lib/music/constants";

export const routeRegistry = [
  {
    id: "home",
    path: "/",
    labelKey: "nav.home",
    component: "home",
    seo: {
      titleKey: "seo.home.title",
      descriptionKey: "seo.home.description",
      keywords: ["Moenotes", "BanG Dream", "Our Notes", "MoeSekai"],
      sitemap: { priority: 1, changefreq: "daily" },
    },
    nav: false,
    searchable: true,
    keywords: ["home", "index", "moenotes"],
  },
  {
    id: "database",
    path: "/database",
    labelKey: "nav.groups.database",
    seo: {
      titleKey: "seo.database.title",
      descriptionKey: "seo.database.description",
      sitemap: { priority: 0.8, changefreq: "daily" },
    },
    nav: { order: 10, icon: "database", shortcut: "g d" },
    searchable: true,
    keywords: ["database", "data", "masterdata"],
    children: [
      {
        id: "characters",
        path: "/characters",
        labelKey: "nav.items.characters",
        component: "characters",
        seo: {
          titleKey: "seo.characters.title",
          descriptionKey: "seo.characters.description",
          sitemap: { priority: 0.8, changefreq: "daily" },
        },
        nav: { order: 10, icon: "users", shortcut: "g c" },
        searchable: true,
        keywords: ["characters", "members", "cast"],
        children: [
          {
            id: "character-detail",
            kind: "dynamic",
            path: "/characters/:id",
            pattern: "/characters/:id",
            parentId: "characters",
            labelKey: "nav.items.characters",
            component: "character-detail",
            seo: {
              titleKey: "seo.characterDetail.title",
              descriptionKey: "seo.characterDetail.description",
              indexable: false,
            },
            nav: false,
            searchable: false,
            staticParams: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10].map((id) => ({
              params: { id: String(id) },
              breadcrumbDetail: { label: `#${id}` },
            })),
          },
        ],
      },
      {
        id: "cards",
        path: "/cards",
        labelKey: "nav.items.cards",
        component: "cards",
        seo: {
          titleKey: "seo.cards.title",
          descriptionKey: "seo.cards.description",
          sitemap: { priority: 0.8, changefreq: "daily" },
        },
        nav: { order: 15, icon: "sparkles" },
        searchable: true,
        keywords: ["cards", "illustration", "gacha"],
        children: [
          {
            id: "card-detail",
            kind: "dynamic",
            path: "/cards/:id",
            pattern: "/cards/:id",
            parentId: "cards",
            labelKey: "nav.items.cards",
            component: "card-detail",
            seo: {
              titleKey: "seo.cardDetail.title",
              descriptionKey: "seo.cardDetail.description",
              indexable: false,
            },
            nav: false,
            searchable: false,
            staticParams: CARD_IDS.map((id) => ({
              params: { id: String(id) },
              breadcrumbDetail: { label: `#${id}` },
            })),
          },
        ],
      },
      {
        id: "support-cards",
        path: "/support-cards",
        labelKey: "nav.items.supportCards",
        component: "support-cards",
        seo: {
          titleKey: "seo.supportCards.title",
          descriptionKey: "seo.supportCards.description",
          sitemap: { priority: 0.8, changefreq: "daily" },
        },
        nav: { order: 18, icon: "sparkles" },
        searchable: true,
        keywords: ["support cards", "support", "gacha"],
        children: [
          {
            id: "support-card-detail",
            kind: "dynamic",
            path: "/support-cards/:id",
            pattern: "/support-cards/:id",
            parentId: "support-cards",
            labelKey: "nav.items.supportCards",
            component: "support-card-detail",
            seo: {
              titleKey: "seo.supportCardDetail.title",
              descriptionKey: "seo.supportCardDetail.description",
              indexable: false,
            },
            nav: false,
            searchable: false,
            staticParams: SUPPORT_CARD_IDS.map((id) => ({
              params: { id: String(id) },
              breadcrumbDetail: { label: `#${id}` },
            })),
          },
        ],
      },
      {
        id: "music",
        path: "/music",
        labelKey: "nav.items.music",
        component: "music",
        seo: {
          titleKey: "seo.music.title",
          descriptionKey: "seo.music.description",
          sitemap: { priority: 0.8, changefreq: "daily" },
        },
        nav: { order: 20, icon: "music", shortcut: "g m" },
        searchable: true,
        keywords: ["music", "songs", "live"],
        children: [
          {
            id: "song-detail",
            kind: "dynamic",
            path: "/music/:id",
            pattern: "/music/:id",
            parentId: "music",
            labelKey: "nav.items.music",
            component: "song-detail",
            seo: {
              titleKey: "seo.songDetail.title",
              descriptionKey: "seo.songDetail.description",
              indexable: false,
            },
            nav: false,
            searchable: false,
            staticParams: MUSIC_IDS.map((id) => ({
              params: { id: String(id) },
              breadcrumbDetail: { label: `#${id}` },
            })),
          },
        ],
      },
      {
        id: "stamps",
        path: "/stamps",
        labelKey: "nav.items.stamps",
        component: "stamps",
        seo: {
          titleKey: "seo.stamps.title",
          descriptionKey: "seo.stamps.description",
          sitemap: { priority: 0.8, changefreq: "daily" },
        },
        nav: { order: 22, icon: "sparkles" },
        searchable: true,
        keywords: ["stamps", "stickers", "emojis"],
      },
      {
        id: "comics",
        path: "/comics",
        labelKey: "nav.items.comics",
        component: "comics",
        seo: {
          titleKey: "seo.comics.title",
          descriptionKey: "seo.comics.description",
          sitemap: { priority: 0.8, changefreq: "daily" },
        },
        nav: { order: 25, icon: "book" },
        searchable: true,
        keywords: ["comics", "manga", "loading screen"],
      },
      {
        id: "items",
        path: "/items",
        labelKey: "nav.items.items",
        component: "items",
        seo: {
          titleKey: "seo.items.title",
          descriptionKey: "seo.items.description",
          sitemap: { priority: 0.8, changefreq: "daily" },
        },
        nav: { order: 26, icon: "archive" },
        searchable: true,
        keywords: ["items", "possessions", "materials", "inventory"],
      },
    ],
  },
  {
    id: "activity",
    path: "/activity",
    labelKey: "nav.groups.activity",
    seo: {
      titleKey: "seo.activity.title",
      descriptionKey: "seo.activity.description",
      sitemap: { priority: 0.7, changefreq: "daily" },
    },
    nav: { order: 20, icon: "calendar", shortcut: "g a" },
    searchable: true,
    keywords: ["activity", "events", "news"],
    children: [
      {
        id: "events",
        path: "/events",
        labelKey: "nav.items.events",
        seo: {
          titleKey: "seo.events.title",
          descriptionKey: "seo.events.description",
          sitemap: { priority: 0.8, changefreq: "daily" },
        },
        nav: { order: 10, icon: "calendar", shortcut: "g e" },
        searchable: true,
        keywords: ["events", "event"],
      },
      {
        id: "news",
        path: "/news",
        labelKey: "nav.items.news",
        seo: {
          titleKey: "seo.news.title",
          descriptionKey: "seo.news.description",
          sitemap: { priority: 0.6, changefreq: "daily" },
        },
        nav: { order: 20, icon: "newspaper" },
        searchable: true,
        keywords: ["news", "notice", "information"],
      },
    ],
  },
  {
    id: "story",
    path: "/story",
    labelKey: "nav.groups.story",
    seo: {
      titleKey: "seo.story.title",
      descriptionKey: "seo.story.description",
      sitemap: { priority: 0.7, changefreq: "weekly" },
    },
    nav: { order: 30, icon: "book", shortcut: "g s" },
    searchable: true,
    keywords: ["story", "scenario"],
    children: [
      {
        id: "main-story",
        path: "/story/main",
        labelKey: "nav.items.mainStory",
        seo: {
          titleKey: "seo.mainStory.title",
          descriptionKey: "seo.mainStory.description",
          sitemap: { priority: 0.6, changefreq: "weekly" },
        },
        nav: { order: 10, icon: "book" },
        searchable: true,
        keywords: ["main story", "scenario"],
      },
      {
        id: "event-story",
        path: "/story/events",
        labelKey: "nav.items.eventStory",
        seo: {
          titleKey: "seo.eventStory.title",
          descriptionKey: "seo.eventStory.description",
          sitemap: { priority: 0.6, changefreq: "weekly" },
        },
        nav: { order: 20, icon: "book" },
        searchable: true,
        keywords: ["event story", "scenario"],
      },
    ],
  },
  {
    id: "tools",
    path: "/tools",
    labelKey: "nav.groups.tools",
    seo: {
      titleKey: "seo.tools.title",
      descriptionKey: "seo.tools.description",
      sitemap: { priority: 0.6, changefreq: "weekly" },
    },
    nav: { order: 40, icon: "wrench", shortcut: "g t" },
    searchable: true,
    keywords: ["tools", "calculator"],
    children: [
      {
        id: "toolbox",
        path: "/tools/toolbox",
        labelKey: "nav.items.toolbox",
        seo: {
          titleKey: "seo.toolbox.title",
          descriptionKey: "seo.toolbox.description",
          sitemap: { priority: 0.5, changefreq: "weekly" },
        },
        nav: { order: 10, icon: "sparkles" },
        searchable: true,
        keywords: ["toolbox", "utilities"],
      },
      {
        id: "design-system",
        path: "/tools/design-system",
        labelKey: "nav.items.designSystem",
        component: "design-system",
        seo: {
          titleKey: "seo.designSystem.title",
          descriptionKey: "seo.designSystem.description",
          sitemap: { priority: 0.3, changefreq: "monthly" },
          indexable: false,
        },
        nav: false,
        searchable: false,
        keywords: ["design system", "style guide", "components"],
      },
    ],
  },
  {
    id: "community",
    path: "/about",
    labelKey: "nav.groups.community",
    component: "about",
    seo: {
      titleKey: "seo.about.title",
      descriptionKey: "seo.about.description",
      sitemap: { priority: 0.5, changefreq: "monthly" },
    },
    nav: { order: 50, icon: "info" },
    searchable: true,
    keywords: ["about", "moesekai"],
    children: [],
  },
] as const satisfies readonly AppRoute[];
